services:
    postgres:
      image: postgres:17
      container_name: eventlerdb
      restart: always
      environment:
        POSTGRES_DB: eventler
        POSTGRES_USER: eventler
        POSTGRES_PASSWORD: eventler
      ports:
        - "5434:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    pgadmin:
      container_name: pgadmin4eventler
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"  
      ports:
        - "5071:80"  
    php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: EventlerPlatform
      restart: always
      volumes:
        - ./:/var/www/html
      ports:
        - "88:80"
volumes:
  postgres_data: